[font]
normal                = { family = "FiraCode Nerd Font", style = "Retina" }
bold                  = { family = "FiraCode Nerd Font", style = "Bold" }
italic                = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic           = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size                  = 16
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor.style]
shape                 = "Block"
blinking              = "Off"

[window]
opacity =  0.90
