# Path to your oh-my-zsh installation.
export "REPOS=$HOME/repos"
export "DOTFILES=$REPOS/dotfiles"
export PATH="$DOTFILES/scripts:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

source <(fzf --zsh)
